### PR TITLE
Move zoom thread init before usage

### PR DESCRIPTION
**Pull request by ocsmit**
Addresses #1 (Hopefully). Not able to test on Linux or Windows at the moment, but fixes zoom issues for Mac.

### CODE REVIEW

**Comment by HuidaeCho** [comment]
@ocsmit I don't understand how moving that part of the code above `if event.ControlDown():`, which doesn't even have any `zoomer` code, addresses #1. I guess, it's more of a timing issue (race condition?) than the actual order of code. The current code ensures non-None `zoomer` after the very first initialization of `zoomer`.

So I guess, on Mac, non-None `zoomer` doesn't mean its thread is alive?

**Comment by ocsmit** [comment]
It's just as perplexing to me as well. In the original code`zoomer._started.is_set()` returns false within the `if` block even though the thread has been initialized.

**Comment by HuidaeCho** [comment]
I think using 1 millisecond for all platforms is cleaner. We still don't know why it happens only on macOS. On the surface, it looks like some sort of a race condition to me, but then is delaying the only solution? What if the same issue happens again even with 1 millisecond delay? More delay?

What's weird is zoomer.start() and zoomer.join() are supposed to be called from the main thread sequentially...

**Comment by ocsmit** [comment]
See comments on issue #1. It is an intentional design for OSX in the original WxPython cpp code. Albeit I do not see any comments as to why within the original code. Neither the UNIX or MSW implementations of the timer.cpp have this limitation.

**Comment by ocsmit** [comment]
With that said, I can certainly revert the last commit to check the platform, but I think given that this is OSX specific within the original cpp it makes sense to me to keep the platform check.

**Comment by HuidaeCho** [comment]
> See comments on issue #1. It is an intentional design for OSX in the original WxPython cpp code. Albeit I do not see any comments as to why within the original code. Neither the UNIX or MSW implementations of the timer.cpp have this limitation.

OK.. Only macOS..

**Comment by HuidaeCho** [comment]
> With that said, I can certainly revert the last commit to check the platform, but I think given that this is OSX specific within the original cpp it makes sense to me to keep the platform check.

Agreed.

**Review by HuidaeCho — APPROVED** [review]

**Comment by HuidaeCho** [comment]
@ocsmit Please test this merged PR. Thanks!

**Pull request merged**
